# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b27cea0bf3a0c1b3f6d53aa65c2abe0b5e7e56891eebaf7d720695ef77f443693f6c1c21e0fde1f76276aa0b885794011c8aab5060e2df8a6355e18af93811

test:
  secret_key_base: f72992e102ff3aab8fdf436ec183652853dbe6f4a025784d3370d6ac353558abdd42c408feb3e07220ff9c6ae4dba18524305aa81e8e27ece8c18eb4db804bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
